name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # Test Job
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3

    # Backend (Python) Testing
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    - name: Upload Python coverage reports
      uses: codecov/codecov-action@v3
      env:
       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
       files: ./coverage.xml
       fail_ci_if_error: true
       debug: true  # Enable debugging

  # Lint Job
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Frontend (Next.js) Linting
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint

    - name: Check TypeScript
      run: npm run type-check

  # Upload Coverage Job
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Display Token (For Debugging Only)
      run: echo "CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: LunarLogician/FInal-Rag-Project-Dep
        debug: true  # Enable debugging
