name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js (adjust version if needed)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Install dependencies
    - name: Install dependencies
      run: |
        npm install

    # Run tests and generate coverage report (using Jest in this case)
    - name: Run tests with coverage
      run: |
        npx jest --coverage

    # Upload coverage report to Codecov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # Ensure this secret is correctly added in GitHub
        files: ./coverage.xml                # Coverage file location
        fail_ci_if_error: true
        slug: "LunarLogician/FInal-Rag-Project-Dep"  # Your GitHub repository slug

